jwt:
  privateKey: classpath:/keys/private-key.pem
  refreshKey: classpath:/keys/private-refresh.pem

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5434/userservicedb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres777!}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.yml
    enabled: true
    liquibase-schema: public

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: user-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

service-token: ${secret-token:999d6327-1b80-4ce4-8e15-b51a21ec912d}

logging:
  level:
    root: INFO
    org.springframework: INFO
    org.hibernate: INFO

server:
  port: 8081